### ISSUE TITLE
the opacity property in Image component should by a doble instead of int

### ISSUE THREAD

**Issue by Multikatz** [stoiveyp/Alexa.NET.APL#44]
In the multimodal creator the values of opacity is the type double

![example](https://user-images.githubusercontent.com/19331804/57328634-90bb8a00-70d7-11e9-9b9b-a823c644a269.png)

Only accepts integers

![secondexample](https://user-images.githubusercontent.com/19331804/57328781-f871d500-70d7-11e9-9a2b-677097b81642.png)

https://github.com/stoiveyp/Alexa.NET.APL/blob/a2a5981b8938ea3d139b8ad03a6b012d11e29748/Alexa.NET.APL/Components/Image.cs#L27

**Comment by stoiveyp** [comment]
Hi @Multikatz - the documentation for Opacity appears to have been removed - are you able to find any?

The problem with APL being in beta is the docs and the editor keep changing, so I'm having to be careful to follow what the docs expect, rather than the more JS-style typing the editor is allowing.

Is the issue here that it doesn't deserialize properly, or does the decimal value actually make a visual difference? (trying to figure out how urgent a fix this is)

**Comment by stoiveyp** [comment]
FYI I've reached out to the Alexa devs on Twitter and raised https://forums.developer.amazon.com/questions/205858/apl-numeric-properties.html on the Alexa forums to get an answer on what's expected with numeric properties - as this has come up a couple of times and I'm hoping for some guidance.

**Comment by stoiveyp** [comment]
Hey @Multikatz - Amazon have got back to me and confirmed that double's are fine as long as the documentation doesn't specifically say integers.

v3.15 has updated opacity, as well as borderradius in frame and the container grow and shrink properties. Thank you 👍
